[package]
name = "chatgptr"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
bacon = "2.13.0"

[dependencies]
dirs = "5.0.1"
reqwest = { version = "0.11.20", features = ["blocking"] }
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["full"] }
